# apropos
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/apropos.1
complete -c apropos -s a --description 'Instead of showing only the title lines, show the complete manual pages, just…'
complete -c apropos -s C --description 'Specify an alternative configuration file in man. conf 5 format.'
complete -c apropos -s c --description 'In a mode, copy the formatted manual pages to the standard output without usi…'
complete -c apropos -s f --description 'Search for all words in expression in manual page names only.'
complete -c apropos -s h --description 'Instead of showing the title lines, show the SYNOPSIS sections, just like man…'
complete -c apropos -s k --description 'Support the full expression syntax.'
complete -c apropos -s l --description 'An alias for mandoc 1 a.  This overrides any earlier f, k, and w options.'
complete -c apropos -s M --description 'Use the colon-separated path instead of the default list of paths searched fo…'
complete -c apropos -s m --description 'Prepend the colon-separated paths to the list of paths searched for makewhati…'
complete -c apropos -s O --description 'Show the values associated with the key outkey instead of the manual descript…'
complete -c apropos -s S --description 'Restrict the search to pages for the specified machine 1 architecture.'
complete -c apropos -s s --description 'Restrict the search to the specified section of the manual.'
complete -c apropos -s w --description 'Instead of showing title lines, show the pathnames of the matching manual pag…'
complete -c apropos -s i --description 'If term is a regular expression, it is evaluated case-insensitively.'

