# man
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/man.1
complete -c man -s a --description 'Display all matching manual pages.'
complete -c man -s C --description 'Use the specified file instead of the default configuration file.'
complete -c man -s c --description 'Copy the manual page to the standard output instead of using more 1 to pagina…'
complete -c man -s f --description 'A synonym for whatis 1.'
complete -c man -s h --description 'Display only the SYNOPSIS lines of the requested manual pages.'
complete -c man -s I --description 'Override the default operating system name for the mdoc 7 \\&Os and for the ma…'
complete -c man -s K --description 'Specify the input encoding.'
complete -c man -s k --description 'A synonym for apropos 1.'
complete -c man -s l --description 'A synonym for mandoc 1 a.  The name arguments are interpreted as filenames.'
complete -c man -s M --description 'Override the list of standard directories which man searches for manual pages.'
complete -c man -s m --description 'Augment the list of standard directories which man searches for manual pages.'
complete -c man -s O --description 'Comma-separated output options.'
complete -c man -s S --description 'Restricts the directories that man will search to those of a specific machine…'
complete -c man -s T --description 'Select the output format.  The default is locale.'
complete -c man -s W --description 'Specify the minimum message level to be reported on the standard error output…'
complete -c man -s w --description 'List the pathnames of the manual pages which man would display for the specif…'

