# mandoc
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mandoc.1
complete -c mandoc -s a --description 'If the standard output is a terminal device and c is not specified, use more …'
complete -c mandoc -s c --description 'Copy the formatted manual pages to the standard output without using more 1 t…'
complete -c mandoc -s f --description 'A synonym for whatis 1.  This overrides any earlier k and l options.'
complete -c mandoc -s h --description 'Display only the SYNOPSIS lines.  Implies c.'
complete -c mandoc -s I --description 'Override the default operating system name for the mdoc 7 \\&Os and for the ma…'
complete -c mandoc -s K --description 'Specify the input encoding.'
complete -c mandoc -s k --description 'A synonym for apropos 1.  This overrides any earlier f and l options.'
complete -c mandoc -s l --description 'A synonym for a.  Also reverts any earlier f and k options.'
complete -c mandoc -s m --description 'Input format.  See Input Formats for available formats.'
complete -c mandoc -s O --description 'Comma-separated output options.'
complete -c mandoc -s T --description 'Output format.  See Output Formats for available formats.'
complete -c mandoc -s W --description 'Specify the minimum message level to be reported on the standard error output…'

